spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:billing?createDatabaseIfNotExist=true;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    hikari:
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
logging:
  level:
    web: DEBUG
    root: DEBUG
kafka:
  consumer:
    bootstrap-servers: "localhost:9092"
    key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    group-id: notify_grp
sms_url: https://651e684e44a3a8aa47684914.mockapi.io/api/post/Notification
